import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { userLoggedIn } from "../auth/authSlice";


export const apiSlice = createApi({
  reducerPath: "api",
  baseQuery: fetchBaseQuery({ baseUrl: process.env.NEXT_PUBLIC_SERVER_URI }),
  endpoints: (builder) => ({
    updateUser: builder.mutation({
        query: ({ name}) => ({
        url: 'update-user-info',
        method: 'PUT',
        body: { name},
        credentials: "include" as const,
      }),
     
    }),

  }),
});

// Export the hooks generated by the API slice
export const { useUpdateUserMutation } = apiSlice